---

  - name: My First Playbook.
    hosts: webservers
    become: true
    tasks:

    - name: Install docker.io (state=present)
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Install python3-pip (state=present)
      apt:
        name: python3-pip
        state: present

    - name: Install docker (state=present)
      pip:
        name: docker
        state: present

    - name: Download and launch a docker web container
      docker_container:
        name: dvwa
        image: cyberxsecurity/dvwa
        state: started
        restart_policy: always
        published_ports: 80:80

    - name: Enable docker service
      systemd:
        name: docker
        enabled: yes